name: Build all own packages
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.list.outputs.packages }}
    steps:
      - uses: actions/checkout@v4

      - id: list
        run: |
          packages=$(ls -1 packages/own | jq -R -s -c 'split("\n")[:-1]')
          echo "packages=$packages" >> "$GITHUB_OUTPUT"

  build-and-publish:
    needs: discover
    uses: ./.github/workflows/build-own.yml
    with:
      packages: ${{ needs.discover.outputs.packages }}
    secrets: inherit
