name: Build and publish package
permissions:
  contents: write

on:
  workflow_call:
    inputs:
      package_path:
        description: 'Path to the package dir, e.g. packages/own/charist'
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      package_path: ${{ inputs.package_path }}

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
